### ISSUE TITLE
Also duplicate post meta data

### ISSUE THREAD

**Issue by gereby** [jchristopher/duplicate-menu#5]
I am using the ubermenu plugin with its various settings. using duplicate-menu all the the post meta data gets not copied to the new instance. if i had a wish i would like to have an option to either duplicate them to the new instance.

all of the UberMenu menu item data is stored in the postmeta table with all the standard menu item data, and is keyed by "_uber_options" (all options for a single menu item are stored in a single serialized meta_value).

**Comment by jchristopher** [comment]
There is an action fired for each Menu item: `duplicate_menu_item`

```php
add_action( 'duplicate_menu_item', function( $menu_item, $args ) {
    // TODO: Duplicate meta here.
}, 10, 2 );
```

**Comment by lkraav** [comment]
Hmm, so this is a self-service opt-in thing huh?

In general, I agree that with plugins like https://github.com/helgatheviking/Nav-Menu-Roles/ storing their configuration, it would've been nice to get it automagically in the duplicate menu as well.
