### ISSUE TITLE
Deprecated: Non-static method DuplicateMenu::options_screen()

### ISSUE THREAD

**Issue by tbuegel** [jchristopher/duplicate-menu#8]
PHP Version 7.1.17: 
Plugin does what it should but I get this warning after plugin install and calling /wp-admin/themes.php?page=duplicate-menu:
( ! ) Deprecated: Non-static method DuplicateMenu::options_screen() should not be called statically in ...class-wp-hook.php on line 286

**Comment by lkraav** [comment]
@jchristopher you up for patching this or need a PR?

**Comment by jchristopher** [comment]
Version `0.2.2` has been released with a fix for this Issue 👍
